# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb58e5ccb30db4f32c8e8cf82ed236e8bfc3d090bbbbb33a29692e47ef5a89c4fbaa67c6448cbca7a65c33f3f6089b8a2c2502386e769240c2c010a30e463999

test:
  secret_key_base: d9c4f47f14978cf68bc6a29baabe8e54dddb8a978b3f304b17dc64d6be73ffc95a85debcbccda652366a3fb28c1ced0384eb93a29927987e37cb5c5a3710b1aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
